CREATE TABLE chara (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT,
	race TEXT,
    job TEXT,
    skills TEXT[],
    str INTEGER,
    dex INTEGER,
    con INTEGER,
    int INTEGER,
    wis INTEGER,
    cha INTEGER,
    userId INTEGER REFERENCES auth(id) ON DELETE CASCADE
)